apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-web-server
  namespace: {{ .Values.namespace }}
  labels:
    app: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: my-nextwebserver:1
        imagePullPolicy: IfNotPresent
        ports: 
          - containerPort: 3000