apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-web-server
  namespace: {{ .Values.namespace }}
  labels:
    app: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: next-js
        image: 313422618945.dkr.ecr.eu-central-1.amazonaws.com/erza-ick-training:dev
        imagePullPolicy: IfNotPresent
        ports: 
          - containerPort: 3000