apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-web-server
  namespace: {{ .Values.namespace }}
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports: 
          - containerPort: {{ .Values.image.containerPort }}